### ISSUE TITLE
Cache is broken.

### ISSUE THREAD

**Issue by SimonSimCity** [ModyQyW/vite-plugin-eslint2#26]
### Describe the bug

Same as in https://github.com/gxmari007/vite-plugin-eslint/issues/11, this extension also suffers from the same problem.

The previous owner solved it by making the cache optionally available. Since this is a striking problem to me, I've disabled the cache. Would be good to have a feedback from you about this. Maybe you've already been working on it and I'm just seeing it wrongly somehow ..?

### Reproduction

I've not yet managed to create a well-defined repo around this, but you should be able to refer any details from the link above.

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 57.21 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 16.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ModyQyW** [comment]
I just had a weekend so I am a bit late here. Sorry about that.

In short, yes, I have tried to solve this problem and rethought this plugin.

To solve this problem, I recommend clearing the cache and restarting `vite`. I think this is an unexpected problem. Since almost everyone runs ESLint in IDE or editor and we can run ESLint in CI, there should not be any ESLint problem when we start `vite`. Besides, you can try to enable `lintOnStart` option, which allows stopping the process when there are ESLint errors.

As I explained upper, you may not need this plugin, as you can run ESLint in IDE, editor, or CI. See more in [FAQ part](https://github.com/ModyQyW/vite-plugin-eslint2#faq).

To dig deeper into this problem, I need a reproduction. But sadly I have no time to build one. If you can kindly provide a reproduction, I will be happy to check what I can do about this problem!

Thanks for your focus on this plugin. :D

**Comment by SimonSimCity** [comment]
For me, having to restart is undesired because some on my team like prototyping but some of our eslint rules require a certain coding style. Their dev-application would have to restart after they fixed a linting error.

After reading that `vite` also doesn't check TypeScript types because of speed, we chose to follow sute with our workflow, means that we will not have a use for this plugin as of now. If anyone else runs into this, you're welcome to continue.

Thanks for your time so far! I use and have built/contributed to some open source tools myself and know a bit of the hassle ☺️

**Comment by ModyQyW** [comment]
If anyone else runs into this, welcome to continue. Please read the upper comments first ⬆️.

Send me a reproduction will be appreciated.
